
server.port=8585

server.servlet.context-path=/workintech

#Actuator
management.info.env.enabled=true
management.endpoints.web.exposure.include=info,health,mappings


info.app.name=workintech
info.app.description=spring boot day 2 Project
info.app.version=v1
